### ISSUE TITLE
Conexion php/javascript

### ISSUE THREAD

**Issue by randylpv** [BeepQuest/api#1]
Buenas tardes

¿Podría por favor mostrar un ejemplo de como realizar la conexión correctamente con php o javascript? 
Ya tengo generados los tokens

Saludos

**Comment by OkuraSt** [comment]
Hola, conexión en los lenguajes que comentas es algo trivial, pero ademas depende de tus necesidades especificas, desde donde estas haciendo la llamada hasta las librerías que puedes utilizar, te dejo algunos links donde puedes ver mas información.

Ejemplos
Javascript con JQuery

http://api.jquery.com/jQuery.ajax/

PHP con file_get_contents

https://stackoverflow.com/questions/2107759/php-file-get-contents-and-setting-request-headers

Recuerda, deben enviarse los tokens en los headers con los keys marcados en la documentacion y la llamada es de tipo json.

**Comment by randylpv** [comment]
$( document ).ready(function() {
    console.log( "ready!" );

	$.ajax({
		url: 'http://api.beepquest.com/v1/question_engine_answers',
		headers: {
			'bqapptok':'xxxx',
			'bqmodtok':'xxx'
		},
		method: 'GET',
		dataType: 'json',
		data: { user: "", initialDate: "2017-01-01",finalDate: "", limit: 10, skip: 20  },
		success: function(data){
		  console.log('succes: '+data);
		}
	  });
		
});

**Comment by randylpv** [comment]
{"message":"Not Found","code":7778,"description":{}}
