### ISSUE TITLE
Consulta a un solo registro 

### ISSUE THREAD

**Issue by wakho** [BeepQuest/api#10]
Hola @OkuraSt , cuando quiero un solo cliente en la Url con query le envío el correo en el "User" :

'http://api.beepquest.com/v1/question-module-answers?user=ejemplo@gmail.com&initialDate=2018-01-01&limit=10'
Se supone que debería mandar solo el cliente solicitado pero me sigue arrojando todos los registros.
puedes apoyarme solo quiero un cliente o varios.

`<?php

$headers =array('BQAPPTOK:1234','BQMODTOK:abcde');

$ch =curl_init('http://api.beepquest.com/v1/question-module-answers?user=ejemplo@gmail.com&initialDate=2018-01-01&limit=10');
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER , true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST , "GET");
$response = curl_exec($ch);
curl_close($ch);
if(!$response) {
return false;
}else{
var_dump($response);
}
?>``

Espero me puedas apoyar Gracias. Saludos !

**Comment by OkuraSt** [comment]
Hola @wakho buenos días

Hice una prueba en tu ambiente, el parámetro para enviar los mails es `users` no ~~`user`~~.

Ya hice la modificación en la documentación.

Saludos
