### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by VHector** [BeepQuest/api#12]
Hace algunos días empecé a recibir la siguiente respuesta:

{
    "name": "AuthorizationError",
    "message": "Permissions error",
    "code": 2200,
    "description": {
        "code": "ENOTFOUND",
        "errno": "ENOTFOUND",
        "syscall": "getaddrinfo",
        "hostname": "undefined",
        "host": "undefined",
        "port": 80
    }
}

No he cambiado nada en el whitelist de las IP's ni en los tokens de los módulos; ¿Ha cambiado algo en los parámetros de la url o es un problema temporal?

**Comment by OkuraSt** [comment]
Hola @VHector gracias por reportar este tema, se trataba de un problema temporal, ya esta restablecida la comunicacion a traves del API, puedes intentarlo nuevamente por favor y si esta todo bien cerremos este issue.

Gracias

**Comment by VHector** [comment]
Muchas gracias por la ayuda!!

Quedó restablecido el servicio.
