### ISSUE TITLE
Configuración de API eliminada

### ISSUE THREAD

**Issue by VHector** [BeepQuest/api#14]
Buenos días.

El día de hoy quise realizar una consulta por medio de Postman y obtuve el siguiente resultado:

{
    "name": "AuthorizationError",
    "message": "Permissions error",
    "code": 2200,
    "description": {
        "message": "An internal error has occurred",
        "code": 5578,
        "description": "Something really wrong happened. Try again later!",
        "extra": {
            "name": "AuthorizationError",
            "message": "Invalid IP: 10.128.0.116",
            "code": 2200
        }
    }
} 

Revisando en la configuración de la API me di cuenta de que no existe ningún token ni nunguna IP en la whitelist. ¿Ha ocurrido algún evento que borró los registros o porque no puedo ver nada de la configuración? ¿Me pueden ayudar a recuperar los tokens y la whitelist por favor?

Saludos

**Comment by OkuraSt** [comment]
Hola buenos dias @VHector estamos verificando los token que comentas no aparecen, con respecto al error que se te esta presentando, puedes confirmarnos que dando de alta la IP que tienes en este momento puedas completar el request?
Te sugerimos tambien evitar compartir tu IP en estos issues ya que son publicos

**Comment by VHector** [comment]
Buen día @OkuraSt, ya agregué la IP que utilizo para realizar las solicitudes pero sigo sin poder completar el request.
Nota: La IP que tiene el mensaje de error recibido no es una la IP que utilizo para realizar las solicitudes, ni es la IP interna de mi equipo, de hecho ahora que realice nuevamente la prueba me devolvió una nueva IP.

**Comment by OkuraSt** [comment]
entiendo @VHector, aunque la IP que tienes que agregar es exactamente la que te regresa el mensaje de error por que esa es sobre la que esta validando, puedes intentarlo por favor y compartirme si ya esta ingresada esa IP cual es el error que te muestra?, si es el mismo, el proceso de agregado de whitelist de ip esta incompleto

**Comment by OkuraSt** [comment]
Si el mensaje cambia a token de app incorrecto por favor agregalo uno nuevo en tu panel por favor @VHector

**Comment by OkuraSt** [comment]
@VHector se realizo una modificacion y estan recuperados ya los token que tenias hasta este momento y toda la configuracion, por favor si te funciona todo correcto cerremos este issue, gracias por reportar

**Comment by VHector** [comment]
Ya estoy recibiendo los datos correctamente sin ingresar un nuevo token. Sin embargo al consultar otros módulos me devuelve el mismo error con una IP diferente.
Estoy utilizando la aplicación Postman para realizar las solicitudes, pero todavía esta semana realizaba las solicitudes sin problemas y solo tenía en la whitelist la IP que tiene organización para salir a internet.

**Comment by OkuraSt** [comment]
te sugiero agregar la IP al whitelist con la que te esta mandando el error, no estoy seguro si pueda ser alguna configuracion que tengas en post man, o algun proxy configurado

**Comment by VHector** [comment]
Agregué la IP que me devuelve el error a la Whitelist y ya puedo recibir los datos correctamente.
Pero como te comenté, estoy utilizando Postman para realizar las pruebas, sin embargo, para poder descargar la información de manera automática utilizo otro software que hace la misma solicitud desde el mismo equipo, pero a diferencia de Postman obtengo este mensaje como respuesta.

HTTP Exception: 
Error en el servidor remoto: (308) Permanent Redirect.
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>

Tengo los mismos tokens y parámetros en ambos casos.

**Comment by OkuraSt** [comment]
Prueba por favor poniendo https en lugar de http en postman

**Comment by VHector** [comment]
Ok, puse https en la ruta de las dos aplicaciones, pero tuve que agregar dos IP's a la whitelist; en este momento ya no tengo problemas con las respuestas, pero no sé si mañana tendré que agregar nuevas IP's a la whitelist, te repito que había estado trabajando de manera normal hasta el martes de esta semana, solo con la IP pública configurada y no se han realizado cambios en la red de mi trabajo.
podemos cerrar el issue, pero si el lunes tengo nuevamente el problemas tendré que reabrirlo, ¿te parece bien?

**Comment by OkuraSt** [comment]
Hubo una configuración nueva sobre nuestros certificados https que pudieron haberte afectado, si te vueve a marcar ip incorrecta deberias agregarla al whitelist como corresponde ya que eso no depende del api sino de tu red o temas externos, no derias tener problemas adicionales con la funcionalidad de API pero de tenerlos puedes abrir el issue correspondiente y con gusto te ayudamos
