### ISSUE TITLE
Problemas al llamar a la api

### ISSUE THREAD

**Issue by Edivald0** [BeepQuest/api#15]
Hola buen dia.

he tenido problemas con la api..
1) se borraron todos los tokens de la plataforma
2) manda este error Warning: Invalid argument supplied for foreach() ... que seria lo del parametro 'list'
Saludos.

**Comment by OkuraSt** [comment]
@Edivald0, deberia estar confirmado ya el funcionamiento correcto de nuestra API, cierro este issue y si tienes problemas adicionales comentanos por aqui

**Comment by Edivald0** [comment]
El problema dice que esta en mi foreach
Mira este es mi codigo:
function detectorHumo(){
    //fecha: año/mes/dia
    include('../php/conexion.php');
    $ch = curl_init();
    #curl_setopt($ch, CURLOPT_URL, 'http://api.beepquest.com/v1/question-module-answers?initialDate=2019-01-01&limit=1000&users=h7082-hk1@accor.com');
    curl_setopt($ch, CURLOPT_URL, 'http://api.beepquest.com/v1/question-module-answers?initialDate=2018-01-01&limit=10000');
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('BQAPPTOK:sHj1DxRzGNQvenI4B84eg8CWnMGzGZvnS9PkVZrI','BQMODTOK :g1YghjE2ilVWrQauK92eKOdiVLktFfIJxqF0p71g'));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $html = curl_exec($ch);
    $data = curl_exec($ch);
    curl_close($ch);
    //var_dump($data);
    //var_dump(json_decode($data));
    echo "<br>01. Control detector de humo<br>";
    $result = json_decode($data,true);
    $contador = 1;
    foreach ($result['list'] as $key ) {
      $sql  = "INSERT INTO 01detectorhumo 
        (firstName, 
        lastname, 
        email, 
        ubicacion1, 
        funciona1, 
        ubicacion2, 
        funciona2, 
        ubicacion3, 
        funciona3, 
        ubicacion4, 
        funciona4, 
        fechaDetectorHumo) 
        VALUES (
          '".$key['user']['firstName']."', 
          '".$key['user']['lastName']."', 
          '".$key['user']['email']."', 
          '".$key['answers']['MenUbicacion1']."', 
          '".$key['answers']['MenFunciona1']."', 
          '".$key['answers']['MenUbicacion2']."', 
          '".$key['answers']['MenFunciona2']."', 
          '".$key['answers']['MenUbicacion3']."', 
          '".$key['answers']['MenFunciona3']."', 
          '".$key['answers']['MenUbicacion4']."', 
          '".$key['answers']['MenFunciona4']."', 
          '".$key['created']."')"
      ;
      if (mysqli_query($conn, $sql)) {
        echo "New record created successfully";
      } else {
        echo "Error: " . $sql . "<br>" . mysqli_error($conn);
      }
      echo "<pre>";
      echo "Registro #".$contador."<br/>";
      print_r($key);
      echo "<hr/>";
      echo "</pre>";
      $contador++;
    }
    //mysqli_close($conn);
  }

**Comment by OkuraSt** [comment]
hola @Edivald0, te comento que se sale de nuestro scope asesorar acerca de código externo a nuestra API, Te sugiero 2 cosas:
- Cambiar en la url HTTP por HTTPS
- Aislar solo el código de consulta al API y verificar que código de error está mandando 

De tener algún error con la llamada al API te podemos seguir ayudando por este medio

**Comment by Edivald0** [comment]
Dice que el parámetro "list" no existe... eso es de la API no?
Notice: Undefined index: list in ...

Warning: Invalid argument supplied for foreach() in...

**Comment by Edivald0** [comment]
fullystring(75) "{"name":"InvalidParamsError","message":"Invalid module token: ","code":125}" object(stdClass)#2 (3) { ["name"]=> string(18) "InvalidParamsError" ["message"]=> string(22) "Invalid module token: " ["code"]=> int(125) }
