### ISSUE TITLE
problemas continuan con los APIs

### ISSUE THREAD

**Issue by Edivald0** [BeepQuest/api#16]
Hola buena tarde.
Continuando con el Issue #15 y haciendo pruebas de codigo salieron varios detalles:

- Utilizando los Tokens de siempre (los que se borraron y pudieron recuperar) y corremos los APIs nos dá un resultado de seguridad asociado a una IP que está cambiando a cada momento.  Hemos tenido que agregar direcciones dinámicas en formato 10.128.x.y  al hacer este punto (agregar la IP al Whitelist) en dicho momento vuelve a funcionar con los tokens históricos.

- AL utilizar nuevos tokens el error de seguridad de IP deja de aparecer. Sin embargo, nosotros al tener mas de 100 tokens no es practico hacer cambios en todos nuestros desarrollos.

En pocas palabras, la plataforma tiene un problema con el whitelist después de traer los antiguos tokens… con los nuevos este error de cambiante IP deja de aparecer, pero sería un esfuerzo monumental de nuestra parte generar nuevos tokens y plancharlos en todos los APIs.

**Comment by OkuraSt** [comment]
@Edivald0 has tenido algun problema adicional? Parece que la ultima comunicacion fue que ya estaban operando normalmente. Recuerda revisar la documentacion de consulta de visitas para el procesamiento adicional que requieren hacer con su informacion.
comentame para poder cerrar este issue

**Comment by Edivald0** [comment]
Hola buen día.
Sigue mandando el error de una ip que es desconocida

string(294) "{"name":"AuthorizationError","message":"Permissions error","code":2200,"description":{"message":"An internal error has occurred","code":5578,"description":"Something really wrong happened. Try again later!","extra":{"name":"AuthorizationError","message":"Invalid IP: 10.128.0.78","code":2200}}}" object(stdClass)#2 (4) { ["name"]=> string(18) "AuthorizationError" ["message"]=> string(17) "Permissions error" ["code"]=> int(2200) ["description"]=> object(stdClass)#900 (4) { ["message"]=> string(30) "An internal error has occurred" ["code"]=> int(5578) ["description"]=> string(49) "Something really wrong happened. Try again later!" ["extra"]=> object(stdClass)#902 (3) { ["name"]=> string(18) "AuthorizationError" ["message"]=> string(23) "Invalid IP: 10.128.0.78" ["code"]=> int(2200) } } } 
02. Iluminacion de emergencia

**Comment by OkuraSt** [comment]
Este mensaje indica que debes agregar la IP al whitelist. *Este no es un error del API* es una parte del proceso de authentication que esta implementado.
Me comentas si te puedo ayudar con algo mas, sino para cerrar este issue.

**Comment by VHector** [comment]
Hola buenos días.
Desde el cambio de certificados (issue #14), he tenido que agregar IP's con formato 10.128.0.x a la whitelist como lo describe @Edivald0; he agregado hasta 10 IP's, para poder obtener la información correcta. 

No tengo proxys configurados y las IP's que he tenido que agregar no complen con el formato de las ip's internas de mi organización (10.12.x.z).

He optado por dejar una lista de IP's y realizar la solicitud varias veces, hasta que la IP coincida con alguna de esa lista y pueda obtener los datos.

Esperando encontrar alguna solución a esta situación me encontre con este issue, en dónde @Edivald0 menciona que cambiando los tokens se corrige el "error". Sin embargo ya cambie el token de dos modulos y sigo con el mismo problema.

¿Se ha revisado esta situación?,
¿Es correcto este funcionamiento, aún cuando las IP's no son utilizadas por nuestra red?,
¿Tengo que realizar alguna modificación? o definitivamente
¿Tengo que agregar las 256 ip's posibles en la whitelist para no tener problemas?

Espero me puedan ayudar, gracias.
![Captura01](https://user-images.githubusercontent.com/44238074/62228005-88938380-b382-11e9-86b7-fb90816eba71.PNG)
![Captura02](https://user-images.githubusercontent.com/44238074/62228006-88938380-b382-11e9-981e-5593f7872593.PNG)
![Captura03](https://user-images.githubusercontent.com/44238074/62228007-88938380-b382-11e9-90c6-1e74dc5028cc.PNG)
