### ISSUE TITLE
Problema en respueta (Token no valido)

### ISSUE THREAD

**Issue by ErnyNet** [BeepQuest/api#17]
Al momento de intentar usar RestSharp regresa el siguiente mensage:
"Responce: {"name":"InvalidParamsError","message":"Invalid app token: ","code":125}"

En el caso de WebClient, HttpWeb y HttpClient:
"The remote server returned an error: (403) Forbidden."

El codigo completo:

using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using RestSharp;

namespace TestingEnviroment
{

    class Request
    {
        public static string AppToken = "apptoken"; //apptoken segun el generado en dashboard
        public static string ModToken = "modtoken"; // modtoken segun el generado en dashboard
        public static string url = "http://api.beepquest.com/v1/question-module-answers";
        public static string urlParameter = "?initialDate=2019-08-08T05:00:00&limit=100";
        public static string limit = "100";
        public static string initialDate = "2019-08-08T05:00:00";
        public static string user = "user"; //email de usuario

        public void RestSharp_Requerst()
        {
            var client = new RestClient(url);
            var requestAPI = new RestRequest();

            Console.WriteLine("RestSharp Test");

            requestAPI.AddParameter("initialDate", initialDate);
            requestAPI.AddParameter("limit", limit);
            requestAPI.AddParameter("user", user);
            requestAPI.AddParameter("BQAPPTOK", AppToken);
            requestAPI.AddParameter("BQMODTOK", ModToken);

            IRestResponse response = client.Execute(requestAPI);
            var jsonContent = response.Content;
            Console.WriteLine("Responce: " + jsonContent);
        }
        public void WebClient_Request()
        {
            try
            {
                Console.WriteLine("WebClient Test");

                var webClient = new WebClient();
                webClient.QueryString.Add("initialDate", initialDate);
                webClient.QueryString.Add("limit", limit);
                webClient.Headers.Add("Content-Type", "application/json");
                webClient.Headers.Add("BQAPPTOK", AppToken);
                webClient.Headers.Add("BQMODTOK", ModToken);

                var responce = webClient.DownloadString(url);
                Console.WriteLine("Responce: " + responce);
            }
            catch (Exception e)
            {
                Console.Out.WriteLine("-ERROR-");
                Console.Out.WriteLine(e.Message);
            }

        }
    
        public void HttpWeb_Request()
        {
            try
            {
                Console.WriteLine("HttpWeb Test");

                var request = (HttpWebRequest)WebRequest.Create(url + urlParameter);
                request.Method = "GET";
                request.ContentType = "application/json";
                request.Headers.Add("BQAPPTOK", AppToken);
                request.Headers.Add("BQMODTOK", ModToken);
                request.Headers.Add("user", user);
                request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;

                var response = (HttpWebResponse)request.GetResponse();

                string jsonContent = string.Empty;
                using (var stream = response.GetResponseStream())
                {
                    using (var sr = new StreamReader(stream))
                    {
                        jsonContent = sr.ReadToEnd();
                    }
                }

                Console.WriteLine("Response: " + jsonContent);
            }
            catch (Exception e)
            {
                Console.WriteLine("-Error-");
                Console.WriteLine(e.Message);
            }
        }

        public void HttpClient_Request()
        {
            try
            {
                Console.WriteLine("HttpClinet Test");

                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    httpClient.DefaultRequestHeaders.Add("BQAPPTOK", AppToken);
                    httpClient.DefaultRequestHeaders.Add("BQMODTOK", ModToken);
                    var response = httpClient.GetStringAsync(new Uri(url + urlParameter)).Result;

                    Console.WriteLine("Response: " + response);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("-Error-");
                Console.WriteLine(e.Message);
            }
        }

    }

    class Program
    {

        static void Main(string[] args)
        {

            string Sdes;
            byte des;
            bool check;
            string yn;

            do
            {
                Request test = new Request();

                Console.Write("API test");
                Console.WriteLine("(1)RestSharp (2)WebClient (3)HttpWeb (4)HttpClient");
                Sdes = Console.ReadLine();
                des = Convert.ToByte(Sdes);

                switch (des)
                {
                    case 1:
                        test.RestSharp_Requerst();

                        break;
                    case 2:
                        test.WebClient_Request();
                        break;
                    case 3:
                        test.HttpWeb_Request();
                        break;
                    case 4:
                        test.HttpClient_Request();
                        break;

                }

                Console.WriteLine("Close? y/n");
                yn = Console.ReadLine();
                if (yn == "n" || yn == "N")
                {
                    check = true;
                }
                else { check = false; }

            } while(check == true);
        }
    }
}

Estoy haciendo algo mal? disculpen la molestia.

**Comment by OkuraSt** [comment]
hola @ErnyNet 

Tienes varios ejemplos en tu mismo codigo, si te basaste en el correspondiente de c# que tenemos en este repositorio veo de forma muy rapida que estas mandando los HEADERS como parametros, aqui el codigo del codigo que deberia ser:

`
                Console.WriteLine(\"\r\n\r\nGET_EXAMPLE_RestSharp: question-module-answers \r\n\");
                var client = new RestClient(url);
                var requestAPI = new RestRequest();

                requestAPI.AddParameter("initialDate", initialDate);
                requestAPI.AddParameter("limit", limit);
                requestAPI.AddHeader("BQAPPTOK", token1);
                requestAPI.AddHeader("BQMODTOK", token2);
                IRestResponse response = client.Execute(requestAPI);

                var jsonContent = response.Content;

                Console.WriteLine("Response: " + jsonContent);
`
