### ISSUE TITLE
consultaModuloDistribuidorConcord

### ISSUE THREAD

**Issue by wakho** [BeepQuest/api#2]
<?php
     $data = array(
  		"user" =>" ", 
  		"initialDate" => "2008-06-01",
        //"finalDate" => "2008-07-21",
  		"limit" => 30,
        "skip" =>0 );
     
	$enviar =  json_encode($data);
    $ch =curl_init('http://api.beepquest.com/YMNn1yJquXm4uv4Os847x8nM0gI79Ztfdw2ayQ3u/oBpMOWVxG713yIpXrbOl7bwVWryRdZARpDgdmBqV');
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST , "GET");
    curl_setopt($ch, CURLOPT_POSTFIELDS,($data, 'myvar_'));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER , true);
	 //curl_setopt($ch, CURLOPT_POSTFIELDS , json_encode($userData));

     
     $response = curl_exec($ch);
     curl_close($ch);
            if(!$response) {
                return false;
            }else{
                var_dump($response);
            }
?>

**Comment by wakho** [comment]
es el código que tengo pero no puedo consumir los datos no entiendo muy bien partiendo de la conexión de su api use el token de la aplicación y del modulo. Me pueden apoyar gracias.

**Comment by OkuraSt** [comment]
No estoy seguro que el código que subiste este completo, puedes editarlo para que se vea mas claro, ademas de ponernos el error que te esta dando por favor

**Comment by OkuraSt** [comment]
@wakho agregamos la carpeta samples donde puedes ver un ejemplo de php con curl.
Voy a cerrar este issue si tienes alguna duda mas puedes abrir uno nuevo.
