### ISSUE TITLE
Consultar la respuesta

### ISSUE THREAD

**Issue by annyDcS27** [BeepQuest/api#21]
Hola

Utilizo una de sus apis para poder consultar las respuesta, pero uno de los módulos me parece solo un Id, mi pregunta esa el Id dela pregunta o Id de la respuesta?
Dejo mi código y lo que me aparece al compilar.

`            url: 'https://api.beepquest.com/v1/question-module-answers',
            method: 'GET',
            headers: {
              'BQAPPTOK': 'BQAPPTOK',
              'BQMODTOK': 'BQMODTOK'
            },
            data:{users:'correo',initialDate:'2022-02-28', finalDate:'2022-02-28',limit:'10',skip:0},
            dataType:"json",`

Nota: no pongo datos como token y correo por seguridad
![beepquest](https://user-images.githubusercontent.com/58090278/157324058-f01b3d9c-8f88-4625-aa8c-1c76871494df.PNG)
.

**Comment by ramonramirezz** [comment]
Hola @annyDcS27, la respuesta que sale en en ejemplo "pregunta1_5" es la respuesta de un campo tipo checklist, y esa id es la id de la opción que se contesto.

**Comment by annyDcS27** [comment]
> Hola @annyDcS27 , la respuesta que sale en ejemplo "pregunta1_5" es la respuesta de un campo tipo checklist, y esa id es la id de la opción que se contesta.

Hola! como puedo saber exactamente la respuesta de esa lista que me aparece? es decir un (bueno, malo etc) ya que si checo en la api por moduleAnswerId me aparece igual un id.

**Comment by ramonramirezz** [comment]
Hola @annyDcS27, para decirte que ya se agrego el nombre de la opción dentro de esa respuesta con la propiedad `name`.

**Comment by annyDcS27** [comment]
> 



> Hola @annyDcS27, la respuesta que sale en en ejemplo "pregunta1_5" es la respuesta de un campo tipo checklist, y esa id es la id de la opción que se contesto.

Va

> Hola @annyDcS27 , para decirte que ya se agrego el nombre de la opción dentro de esa respuesta con la propiedad `name`.

Vale muchas gracias, trabaje en esto, cualquier duda te molesto, gracias!
