### ISSUE TITLE
Status 500 Interval Sever Error  - Endpoint -> https://api.beepquest.com/v1/visit-answers

### ISSUE THREAD

**Issue by katgzco** [BeepQuest/api#22]
Buenas noches, he utilizado el API en estos días sin problemas pero el día de hoy estoy recibiendo el siguiente response:
{
    "message": "An internal error has occurred",
    "code": 5578,
    "description": "Something really wrong happened. Try again later!",
    "extra": {}
}
Quedo pendiente a su respuesta, muchas gracias,

**Comment by ramonramirezz** [comment]
@katgzco Hola buen día,  gracias por tu observación y detectamos una validación que no teniamos contemplada, pero ya deberias de poder utilizar ese endpoint sin problemas. 

Cierro este issue y si tienes problemas adicionales comentanos por aqui.
