### ISSUE TITLE
Error en la API

### ISSUE THREAD

**Issue by Ang3lino** [BeepQuest/api#23]
Buen dia, he estado utilizado la API en estos días sin problemas pero el día de hoy estoy recibiendo la siguiente response:

```
{
"message": "An internal error has occurred",
"code": 5578,
"description": "Something really wrong happened. Try again later!",
"extra": {}
}
```

Quedo pendiente a su respuesta, muchas gracias.

**Comment by ramonramirezz** [comment]
Hola @Ang3lino  lo siento por no contestar antes, subimos algunas actualizaciones que podia aver solucionado tu escenario, pero si sigue persistiendo el error, dinos que endpoint estas intentando consultar.

**Comment by ramonramirezz** [comment]
Por falta de inactividad de respuesta cierro este issue, si tiene sun comentario no los puedes dejar saber.
