### ISSUE TITLE
apibeeb

### ISSUE THREAD

**Issue by wakho** [BeepQuest/api#6]
Hola vi los ejemplos en php y ahora me arroja un error de permiso. Supongo que sera algo de la seguridad de con la IP me pueden apoyar. 
``<?php
    
    $headers =array('BQAPPTOK:xxxxx','xxxxx');
    $ch =curl_init('http://api.beepquest.com/v1/question-module-answers?initialDate=2018-01-01&limit=10');
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER , true);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST , "GET");
     
     $response = curl_exec($ch);
     curl_close($ch);
            if(!$response) {
                return false;
            }else{
                var_dump($response);
            }
?>´´
Respuesta:

tring(298) "{"name":"AuthorizationError","message":"Permissions error","code":2200,"description":{"message":"An internal error has occurred","code":5578,"description":"Something really wrong happened. Try again later!","extra":{"name":"AuthorizationError","message":"Invalid IP: 201.140.113.226","code":2200}}}"

**Comment by OkuraSt** [comment]
Claro @wakho, debes configurar tu ip en el panel de la aplicación.
En el panel GH te vas a General > Configuración de Api.
La agregas en la sección IPWhitelist.

Me comentas si te funciona.

**Comment by wakho** [comment]
Estaba agregando mi ip privada pero he utilizado la publica y pude obtener los datos gracias, continuare haciendo algunas pruebas.  Buen día.

**Comment by wakho** [comment]
Hola @OkuraSt , cuando quiero un solo cliente en la Url con query   le envío el correo en el "User" :  

**'http://api.beepquest.com/v1/question-module-answers?user=ejemplo@gmail.com&initialDate=2018-01-01&limit=10'** 
Se supone que debería mandar solo el cliente solicitado pero me sigue arrojando todos los registros. 
puedes apoyarme solo quiero un cliente o varios.  
`
<?php
    
    $headers =array('BQAPPTOK:1234','BQMODTOK:abcde');
  
    $ch =curl_init('http://api.beepquest.com/v1/question-module-answers?user=ejemplo@gmail.com&initialDate=2018-01-01&limit=10');
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER , true);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST , "GET");
   
 $response = curl_exec($ch);
     curl_close($ch);
            if(!$response) {
                return false;
            }else{
                var_dump($response);
            }
?>
`

**Comment by OkuraSt** [comment]
Lo vemos en el nuevo issue...
